### ISSUE TITLE
Show list of artisan names instead of box view in the categories.jsp page

### ISSUE THREAD

**Issue by gopalgoel19** [gopalgoel19/ncore#2]

**Comment by devanshu0987** [comment]
![categories](https://user-images.githubusercontent.com/13786091/37444730-3753ff70-2839-11e8-8622-b7ce46dc97ae.png)

**Comment by devanshu0987** [comment]
Looks like this. Approve then i will send a PR

**Comment by gopalgoel19** [comment]
IMO, if we write category next to the name and the rating next to the category, it will look better.
Right now, we have too much blank space. Unnecessary scrolling.

**Comment by gopalgoel19** [comment]
![screenshot 205](https://user-images.githubusercontent.com/11490517/37578440-d4ccc9da-2b5e-11e8-81fd-446fab8f846c.png)
